[build]
  publish = "."

[[redirects]]
  from = "https://www.samchonbaegwan.co.kr/*"
  to = "https://samchonbaegwan.co.kr/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/:splat/"
  status = 301
  force = false

[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "index, follow"
